### PR TITLE
Added basic server

### PR DESCRIPTION
**Pull request by MitMaro**
Basic server, doesn't do much yet.

### CODE REVIEW

**Comment by whymarrh** [comment]
Will any particular server (framework) be used?

**Comment by MitMaro** [comment]
Was going to base everything from here on out on the existing PRs and decisions. So hapi.js eventually. #16 is still probably very relevant, I just wanted to get the server side basic, such as build, eslint, etc. working. Forgot that we used an api folder (thought it was server), I will move the folder before merge.

**Comment by whymarrh** [comment]
Fair enough, thought you might want to refresh a few of the decisions. (The
other PR needs a refresh anyhow.)

**Comment by MitMaro** [comment]
Going to keep server but bring over some of the things form the other PRs at a later date.

**Pull request merged**
